include:
- src/
- pom.xml
kind: ArchiveUploadSpec
name: helloworld-java

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: helloworld-java-127w
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: java
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://helloworld-java
status:
  buildstatus: pending

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hello-java
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 1
      MinScale: 0
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: java
    namespace: default
  package:
    functionName: io.fission.HelloWorld
    packageref:
      name: helloworld-java-127w
      namespace: default
  resources: {}
  secrets: null
